title: Linguagem de Programação - ECT/UFRN
logo: /assets/img/logo_ect.png
description: Slides da disciplina de Linguagem de Programação da ECT/UFRN.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme