project:
  title: "Linguagem de Programação - ECT/UFRN"
  type: website
  output-dir: .

author: "Prof. Bruno Silva"
institute: "ECT/UFRN"

format:
  revealjs:
    theme: default
    logo: assets/img/logo_ect.png
    css: assets/css/logo.css
    footer: "ECT2303 - Linguagem de Programação"
    slide-level: 2

